[package]
name = "bevy_def"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy_app = "0.16"
bevy_asset = "0.16"
bevy_ecs = "0.16"
bevy_reflect = "0.16"
bevy_log = "0.16"
bevy_platform = "0.16"
bevy_ptr = "0.16"

[dev-dependencies]
bevy = "0.16"